// packages/vue/src/components/Selector.vue
<script setup lang="ts">
import { computed, onMounted, onBeforeUnmount, onUpdated, useTemplateRef } from "vue";
import {
  exactStatusCopy,
  mountSelector,
  selectorGroups,
  type SelectorOption,
} from "@gamut-plane/ui";
const props = defineProps<{
  id: string;
  label: string;
  value: string;
  options: readonly SelectorOption[];
  disabled: boolean;
  inlineLabel?: boolean;
  requestCurrent?: boolean;
}>();
const emit = defineEmits<{ request: [value: string] }>();
const trigger = useTemplateRef<HTMLButtonElement>("trigger");
const popup = useTemplateRef<HTMLDivElement>("popup");
const groups = computed(() => selectorGroups(props.options));
let binding: ReturnType<typeof mountSelector> | undefined;
onMounted(() => {
  binding = mountSelector(trigger.value!, popup.value!, () => ({
    ...props,
    request: (value) => emit("request", value),
  }));
});
onUpdated(() => binding?.reconcile());
onBeforeUnmount(() => binding?.dispose());
</script>
<template>
  <div class="gp-selector">
    <label :id="`${id}-label`" :for="id">{{ label }}</label>
    <button
      ref="trigger"
      :id="id"
      type="button"
      role="combobox"
      :aria-labelledby="`${id}-label`"
      aria-expanded="false"
      aria-haspopup="listbox"
      :aria-controls="`${id}-list`"
      :aria-describedby="
        options.find((option) => option.value === value)?.description
          ? `${id}-description`
          : undefined
      "
      :disabled="disabled"
    >
      <span v-if="inlineLabel" class="gp-selector-inline-label" aria-hidden="true">{{
        label
      }}</span>
      <span>{{ options.find((option) => option.value === value)?.label }}</span
      ><span aria-hidden="true">▾</span>
    </button>
    <span
      v-if="options.find((option) => option.value === value)?.description"
      :id="`${id}-description`"
      data-gp-visually-hidden
      >{{ options.find((option) => option.value === value)?.description }}</span
    >
    <div
      ref="popup"
      :id="`${id}-list`"
      class="gp-selector-popup"
      role="listbox"
      :aria-labelledby="`${id}-label`"
      popover="auto"
      hidden
    >
      <div
        v-for="(group, groupIndex) in groups"
        :key="groupIndex"
        :role="group.label ? 'group' : undefined"
        :aria-labelledby="group.label ? `${id}-group-${groupIndex}` : undefined"
      >
        <div v-if="group.label" :id="`${id}-group-${groupIndex}`" class="gp-selector-heading">
          {{ group.label }}
        </div>
        <div
          v-for="{ option, index } in group.options"
          :key="option.value"
          :id="`${id}-option-${index}`"
          role="option"
          :data-value="option.value"
          :aria-selected="option.value === value"
          :aria-label="
            option.status
              ? `${option.label}, gamut status ${exactStatusCopy[option.status]}`
              : `${option.optionLabel ?? option.label}${option.description ? `. ${option.description}` : ''}`
          "
        >
          <span class="gp-selector-check" aria-hidden="true">{{
            option.value === value ? "✓" : ""
          }}</span>
          <span class="gp-selector-name">{{ option.optionLabel ?? option.label }}</span>
          <span v-if="option.coordinates" class="gp-selector-coordinates" aria-hidden="true">{{
            option.coordinates
          }}</span>
          <span v-if="option.status" class="gp-selector-status" :data-gp-status="option.status">{{
            option.status ? exactStatusCopy[option.status] : ""
          }}</span>
        </div>
      </div>
    </div>
  </div>
</template>

// packages/react/src/components/Selector.tsx
import { useLayoutEffect, useRef } from "react";
import {
  exactStatusCopy,
  mountSelector,
  selectorGroups,
  type SelectorInput,
} from "@gamut-plane/ui";
import { useCommitted } from "../hooks/useCommitted.js";

export function Selector(
  props: SelectorInput & { id: string; label: string; inlineLabel?: boolean },
) {
  const trigger = useRef<HTMLButtonElement>(null);
  const popup = useRef<HTMLDivElement>(null);
  const current = useCommitted(props);
  const binding = useRef<ReturnType<typeof mountSelector> | null>(null);
  useLayoutEffect(() => {
    const mounted = mountSelector(trigger.current!, popup.current!, () => current.current!);
    binding.current = mounted;
    return () => {
      mounted.dispose();
      binding.current = null;
    };
  }, [current]);
  useLayoutEffect(() => {
    binding.current?.reconcile();
  });
  return (
    <div className="gp-selector">
      <label id={`${props.id}-label`} htmlFor={props.id}>
        {props.label}
      </label>
      <button
        ref={trigger}
        id={props.id}
        type="button"
        role="combobox"
        aria-labelledby={`${props.id}-label`}
        aria-expanded="false"
        aria-haspopup="listbox"
        aria-controls={`${props.id}-list`}
        aria-describedby={
          props.options.find((option) => option.value === props.value)?.description
            ? `${props.id}-description`
            : undefined
        }
        disabled={props.disabled}
      >
        {props.inlineLabel && (
          <span className="gp-selector-inline-label" aria-hidden="true">
            {props.label}
          </span>
        )}
        <span>{props.options.find((option) => option.value === props.value)?.label}</span>
        <span aria-hidden="true">▾</span>
      </button>
      {props.options.find((option) => option.value === props.value)?.description && (
        <span id={`${props.id}-description`} data-gp-visually-hidden="">
          {props.options.find((option) => option.value === props.value)?.description}
        </span>
      )}
      <div
        ref={popup}
        id={`${props.id}-list`}
        className="gp-selector-popup"
        role="listbox"
        aria-labelledby={`${props.id}-label`}
        popover="auto"
        hidden
      >
        {selectorGroups(props.options).map((group, groupIndex) => (
          <div
            key={groupIndex}
            role={group.label ? "group" : undefined}
            aria-labelledby={group.label ? `${props.id}-group-${groupIndex}` : undefined}
          >
            {group.label && (
              <div id={`${props.id}-group-${groupIndex}`} className="gp-selector-heading">
                {group.label}
              </div>
            )}
            {group.options.map(({ option, index }) => (
              <div
                key={option.value}
                id={`${props.id}-option-${index}`}
                role="option"
                data-value={option.value}
                aria-selected={option.value === props.value}
                aria-label={
                  option.status
                    ? `${option.label}, gamut status ${exactStatusCopy[option.status]}`
                    : `${option.optionLabel ?? option.label}${option.description ? `. ${option.description}` : ""}`
                }
              >
                <span className="gp-selector-check" aria-hidden="true">
                  {option.value === props.value ? "✓" : ""}
                </span>
                <span className="gp-selector-name">{option.optionLabel ?? option.label}</span>
                {option.coordinates && (
                  <span className="gp-selector-coordinates" aria-hidden="true">
                    {option.coordinates}
                  </span>
                )}
                {option.status && (
                  <span className="gp-selector-status" data-gp-status={option.status}>
                    {option.status ? exactStatusCopy[option.status] : ""}
                  </span>
                )}
              </div>
            ))}
          </div>
        ))}
      </div>
    </div>
  );
}
