// packages/react/src/components/ColorChannelControl.tsx
import { presentationStyle } from "../model/presentationStyle.js";

import { useLayoutEffect, useRef, useState, type CSSProperties } from "react";
import { gpAttribute, gpPart, mountRange } from "@gamut-plane/ui";
import {
  channelSections,
  channelThresholds,
  channelWarning,
  PICKER_SLIDER_DEFAULT_TRACK_WIDTH,
  PICKER_SLIDER_FIELD_INSET,
  PICKER_SLIDER_TRACK_HEIGHT,
  PICKER_SLIDER_THUMB_TOP,
  PICKER_SLIDER_THUMB_WIDTH,
  PICKER_SLIDER_WARNING_TOP,
  PICKER_WARNING_GLYPH_SIZE,
  type LinearControlInterval,
  type LinearControlMarker,
} from "@gamut-plane/render";
import { useCommitted } from "../hooks/useCommitted.js";
import { NumericInput } from "./NumericInput.js";
import { GamutWarningGlyph } from "./GamutWarningGlyph.js";

export interface ColorChannelControlProps {
  id: string;
  channel: "H" | "L" | "C";
  label: string;
  value: number;
  min: number;
  max: number;
  step: number;
  precision: number;
  gradient: string;
  intervals: readonly LinearControlInterval[];
  markers?: readonly LinearControlMarker[];
  boundaryPreviewColor?: string;
  boundaryPreviewTone?: LinearControlInterval["tone"];
  overflowMax?: boolean;
  help?: string | undefined;
  warningVisible: boolean;
  warningPosition: number;
  normalizeValue?: (value: number) => number;
  onInput: (value: number) => void;
  onComplete: (value: number) => void;
  onCancel: (() => void) | undefined;
  onInteraction?: ((active: boolean) => void) | undefined;
}

const geometryStyle = {
  "--picker-warning-size": `${PICKER_WARNING_GLYPH_SIZE}px`,
  "--picker-slider-field-inset": `${PICKER_SLIDER_FIELD_INSET}px`,
  "--picker-slider-track-height": `${PICKER_SLIDER_TRACK_HEIGHT}px`,
  "--picker-slider-thumb-top": `${PICKER_SLIDER_THUMB_TOP}px`,
  "--picker-slider-thumb-width": `${PICKER_SLIDER_THUMB_WIDTH}px`,
  "--picker-slider-warning-top": `${PICKER_SLIDER_WARNING_TOP}px`,
};

export function ColorChannelControl(props: ColorChannelControlProps) {
  const {
    id,
    channel,
    label,
    value,
    min,
    max,
    step,
    precision,
    gradient,
    intervals,
    markers = [],
    boundaryPreviewColor,
    boundaryPreviewTone,
    overflowMax,
    help,
    warningVisible,
    warningPosition,
    onComplete,
    onCancel,
  } = props;
  const current = useCommitted({ ...props, onInteraction: props.onInteraction });
  const range = useRef<HTMLInputElement>(null);
  const track = useRef<HTMLDivElement>(null);
  const binding = useRef<ReturnType<typeof mountRange> | null>(null);
  const [width, setWidth] = useState(PICKER_SLIDER_DEFAULT_TRACK_WIDTH);
  const bounded = Math.min(max, Math.max(min, value));
  const sections = channelSections(intervals);
  const boundaryPreviewSection = sections.find(
    (section) => section.tone === boundaryPreviewTone && section.end < 1,
  );
  const thresholds = channelThresholds(sections);
  const { placement, obstacles } = channelWarning(warningPosition, width, markers, thresholds);
  const helpId = help ? `${id}-help` : undefined;
  const warningId = warningVisible ? `${id}-gamut-warning` : undefined;
  const describedBy = [helpId, warningId].filter(Boolean).join(" ") || undefined;
  const warningStyle: CSSProperties & Record<string, string | number | undefined> = {
    display: warningVisible ? undefined : "none",
    "--picker-slider-warning-position": `${placement.positionPercent.toFixed(4)}%`,
    "--picker-slider-warning-thumb-offset": `${placement.thumbOffset.toFixed(4)}px`,
    "--picker-slider-warning-side-offset": `${placement.sideOffset}px`,
    "--picker-slider-warning-edge": `${placement.edge}px`,
  };
  useLayoutEffect(() => {
    const mounted = mountRange(range.current!, () => current.current!);
    binding.current = mounted;
    const measure = () => {
      const measured = track.current!.getBoundingClientRect().width;
      if (measured > 0)
        setWidth((previous) => (Math.abs(previous - measured) > 0.25 ? measured : previous));
    };
    const observer = typeof ResizeObserver === "undefined" ? null : new ResizeObserver(measure);
    observer?.observe(track.current!);
    measure();
    return () => {
      binding.current = null;
      mounted.dispose();
      observer?.disconnect();
    };
  }, [current]);
  useLayoutEffect(() => {
    binding.current?.reconcile();
  });
  return (
    <div
      className="gpr-channel-control"
      data-gp-part={gpPart.channel}
      data-gp-channel={channel.toLowerCase()}
      data-gp-overflow={String(value < min || value > max)}
      data-picker-control={channel.toLowerCase()}
      data-instrument-overflow={String(value < min || value > max)}
      data-warning-visible={String(warningVisible)}
      style={presentationStyle(geometryStyle)}
    >
      <header className="gpr-channel-control-header" data-gp-part={gpPart.channelHeader}>
        <label htmlFor={id}>
          <span>{channel}</span>
          {label}
        </label>
        <NumericInput
          className="gpr-channel-control-number"
          aria-label={`${label} numeric value`}
          aria-describedby={describedBy}
          value={value}
          min={min}
          max={overflowMax ? undefined : max}
          step={step}
          precision={precision}
          onComplete={onComplete}
          onCancel={onCancel}
        />
      </header>
      <div
        ref={track}
        className="gpr-channel-control-track"
        data-gp-part={gpPart.channelTrack}
        dir="ltr"
      >
        <span
          className="gpr-channel-control-field"
          data-gp-part={gpPart.channelField}
          style={{ backgroundImage: gradient }}
        />
        <span className="gpr-channel-control-gamut-ranges" aria-hidden="true">
          {sections.map((section, index) => (
            <span
              key={`${section.tone}-${index}`}
              className={`gpr-channel-control-gamut-range gpr-channel-control-gamut-range--${section.tone}`}
              data-gp-part={gpPart.gamutInterval}
              data-gp-gamut={section.tone}
              style={{
                left: `${section.start * 100}%`,
                width: `${(section.end - section.start) * 100}%`,
              }}
              data-gamut-range={section.tone}
              data-range-start={section.start}
              data-range-end={section.end}
            />
          ))}
        </span>
        {markers.map((marker) => (
          <span key={marker.id} className="gpr-sr-only" data-gp-visually-hidden="">
            {marker.label}
          </span>
        ))}
        <span
          className="gpr-channel-control-warning"
          data-gp-part={gpPart.warning}
          data-gp-warning={String(warningVisible)}
          style={warningStyle}
          data-gamut-warning="linear"
          data-warning-channel={channel.toLowerCase()}
          data-warning-position={Math.min(1, Math.max(0, warningPosition))}
          data-warning-side={placement.side}
          data-warning-obstacle-count={obstacles.length}
          data-visible={String(warningVisible)}
          aria-hidden="true"
        >
          <GamutWarningGlyph />
        </span>
        <input
          ref={range}
          id={id}
          className="gpr-channel-control-range"
          data-gp-part={gpPart.nativeRange}
          dir="ltr"
          type="range"
          aria-label={label}
          aria-describedby={describedBy}
          defaultValue={bounded}
          min={min}
          max={max}
          step={step}
          onBlur={(event) => {
            event.currentTarget.removeAttribute("data-pointer-focus");
            event.currentTarget.removeAttribute(gpAttribute.pointerFocus);
          }}
          onPointerDown={(event) => {
            if (event.pointerType !== "mouse" || event.button === 0) {
              event.currentTarget.dataset.pointerFocus = "";
              event.currentTarget.setAttribute(gpAttribute.pointerFocus, "");
            }
          }}
          onKeyDown={(event) => {
            event.currentTarget.removeAttribute("data-pointer-focus");
            event.currentTarget.removeAttribute(gpAttribute.pointerFocus);
          }}
        />
        {boundaryPreviewSection && boundaryPreviewColor && (
          <span className="gpr-channel-control-boundary-preview-position" aria-hidden="true">
            <span
              className="gpr-channel-control-boundary-preview"
              data-gp-part={gpPart.boundaryPreview}
              style={{
                left: `${boundaryPreviewSection.end * 100}%`,
                background: boundaryPreviewColor,
              }}
              data-slider-boundary-preview=""
            />
          </span>
        )}
      </div>
      {help && (
        <p id={helpId} className="gpr-channel-control-help">
          {help}
        </p>
      )}
      {warningId && (
        <span id={warningId} className="gpr-sr-only" data-gp-visually-hidden="">
          Outside Display P3
        </span>
      )}
    </div>
  );
}

// packages/vue/src/components/ColorChannelControl.vue
<script setup lang="ts">
import { gpAttribute, gpPart, mountRange } from "@gamut-plane/ui";
import { useResizeObserver } from "@vueuse/core";
import { computed, onBeforeUnmount, onMounted, ref, watch } from "vue";

import NumericInput from "./NumericInput.vue";
import GamutWarningGlyph from "./GamutWarningGlyph.vue";
import {
  PICKER_SLIDER_DEFAULT_TRACK_WIDTH,
  PICKER_SLIDER_FIELD_INSET,
  PICKER_SLIDER_TRACK_HEIGHT,
  PICKER_SLIDER_THUMB_TOP,
  PICKER_SLIDER_THUMB_WIDTH,
  PICKER_SLIDER_WARNING_TOP,
  PICKER_WARNING_GLYPH_SIZE,
} from "@gamut-plane/render";
import {
  channelSections,
  channelThresholds,
  channelWarning,
  type LinearControlInterval,
  type LinearControlMarker,
} from "@gamut-plane/render";
export type { LinearControlInterval, LinearControlMarker } from "@gamut-plane/render";

const props = withDefaults(
  defineProps<{
    id: string;
    label: string;
    channel: "L" | "C" | "H";
    modelValue: number;
    min: number;
    max: number;
    step: number;
    gradient: string;
    normalizeValue?: (value: number) => number;
    precision?: number;
    markers?: LinearControlMarker[];
    intervals?: LinearControlInterval[];
    boundaryPreviewColor?: string;
    boundaryPreviewTone?: LinearControlInterval["tone"];
    overflowMax?: boolean;
    help?: string;
    warningVisible?: boolean;
    warningLabel?: string;
    warningPosition?: number;
  }>(),
  {
    precision: 3,
    markers: () => [],
    intervals: () => [],
    overflowMax: false,
    help: "",
    warningVisible: false,
    warningLabel: "",
    warningPosition: 0,
  },
);

const emit = defineEmits<{
  "update:modelValue": [value: number];
  commit: [value: number];
  cancel: [];
  "range-interaction": [active: boolean];
}>();

const helpId = computed(() => (props.help ? `${props.id}-help` : undefined));
const warningDescriptionId = computed(() =>
  props.warningVisible && props.warningLabel ? `${props.id}-gamut-warning` : undefined,
);
const describedBy = computed(
  () => [helpId.value, warningDescriptionId.value].filter(Boolean).join(" ") || undefined,
);
const boundedModelValue = computed(() => clamp(props.modelValue));
const isOutsideInstrument = computed(
  () => props.modelValue < props.min || props.modelValue > props.max,
);
const numericMax = computed<number | undefined>(() => (props.overflowMax ? undefined : props.max));
const trackElement = ref<HTMLElement>();
const rangeElement = ref<HTMLInputElement>();
const trackWidth = ref(PICKER_SLIDER_DEFAULT_TRACK_WIDTH);
const displayedRangeValue = ref(boundedModelValue.value);
let rangeBinding: ReturnType<typeof mountRange> | undefined;
const instrumentStyle = {
  "--picker-warning-size": `${PICKER_WARNING_GLYPH_SIZE}px`,
  "--picker-slider-field-inset": `${PICKER_SLIDER_FIELD_INSET}px`,
  "--picker-slider-track-height": `${PICKER_SLIDER_TRACK_HEIGHT}px`,
  "--picker-slider-thumb-top": `${PICKER_SLIDER_THUMB_TOP}px`,
  "--picker-slider-thumb-width": `${PICKER_SLIDER_THUMB_WIDTH}px`,
  "--picker-slider-warning-top": `${PICKER_SLIDER_WARNING_TOP}px`,
};
const guideSections = computed(() => channelSections(props.intervals));
const boundaryPreviewSection = computed(() =>
  guideSections.value.find(
    (section) => section.tone === props.boundaryPreviewTone && section.end < 1,
  ),
);
const guideThresholds = computed(() => channelThresholds(guideSections.value));
const warning = computed(() =>
  channelWarning(props.warningPosition, trackWidth.value, props.markers, guideThresholds.value),
);
const warningPlacement = computed(() => warning.value.placement);
const warningObstacles = computed(() => warning.value.obstacles);
const warningStyle = computed<Record<string, string>>(() => {
  const position = warningPlacement.value;
  return {
    "--picker-slider-warning-position": `${position.positionPercent.toFixed(4)}%`,
    "--picker-slider-warning-thumb-offset": `${position.thumbOffset.toFixed(4)}px`,
    "--picker-slider-warning-side-offset": `${position.sideOffset}px`,
    "--picker-slider-warning-edge": `${position.edge}px`,
  };
});

function updateTrackWidth(width: number): void {
  if (width > 0 && Math.abs(width - trackWidth.value) > 0.25) trackWidth.value = width;
}

function updateTrackBounds(): void {
  const bounds = trackElement.value?.getBoundingClientRect();
  if (!bounds) return;
  updateTrackWidth(bounds.width);
}

onMounted(() => {
  rangeBinding = mountRange(rangeElement.value!, () => ({
    value: boundedModelValue.value,
    min: props.min,
    max: props.max,
    ...(props.normalizeValue ? { normalizeValue: props.normalizeValue } : {}),
    onInput: (value) => emit("update:modelValue", value),
    onComplete: (value) => {
      emit("update:modelValue", value);
      emit("commit", value);
    },
    onInteraction: (active) => emit("range-interaction", active),
  }));
  updateTrackBounds();
  useResizeObserver(trackElement, ([entry]) => {
    if (entry) updateTrackWidth(entry.contentRect.width);
  });
});

function clamp(value: number): number {
  return Math.min(props.max, Math.max(props.min, value));
}

function markPointerFocus(event: PointerEvent): void {
  if (event.pointerType === "mouse" && event.button !== 0) return;
  rangeElement.value?.setAttribute("data-pointer-focus", "");
  rangeElement.value?.setAttribute(gpAttribute.pointerFocus, "");
}

function clearPointerFocus(): void {
  rangeElement.value?.removeAttribute("data-pointer-focus");
  rangeElement.value?.removeAttribute(gpAttribute.pointerFocus);
}

function sectionStyle(section: LinearControlInterval): Record<string, string> {
  return { left: `${section.start * 100}%`, width: `${(section.end - section.start) * 100}%` };
}

watch(
  () => [props.modelValue, props.min, props.max, props.normalizeValue],
  () => {
    rangeBinding?.reconcile();
    // Vue's value binding must reflect the controller's native value after feedback.
    displayedRangeValue.value = rangeElement.value?.valueAsNumber ?? boundedModelValue.value;
  },
  { flush: "sync" },
);

onBeforeUnmount(() => {
  rangeBinding?.dispose();
  rangeBinding = undefined;
});
</script>

<template>
  <div
    class="channel-control"
    :data-gp-part="gpPart.channel"
    :data-gp-channel="channel.toLowerCase()"
    :data-gp-overflow="String(isOutsideInstrument)"
    :data-picker-control="channel.toLowerCase()"
    :data-instrument-overflow="isOutsideInstrument ? 'true' : 'false'"
    :data-warning-visible="warningVisible ? 'true' : 'false'"
    :style="instrumentStyle"
  >
    <header class="channel-control__header" :data-gp-part="gpPart.channelHeader">
      <label :for="id">
        <span>{{ channel }}</span>
        {{ label }}
      </label>
      <NumericInput
        class="channel-control__number"
        :aria-label="`${label} numeric value`"
        :aria-describedby="describedBy"
        :model-value="modelValue"
        :precision="precision"
        :min="min"
        :max="numericMax"
        :step="step"
        @update:model-value="emit('update:modelValue', $event)"
        @commit="emit('commit', $event)"
        @cancel="emit('cancel')"
      />
    </header>

    <div
      ref="trackElement"
      class="channel-control__track"
      :data-gp-part="gpPart.channelTrack"
      @pointerenter="updateTrackBounds"
    >
      <span
        class="channel-control__field"
        :data-gp-part="gpPart.channelField"
        :style="{ backgroundImage: gradient }"
      />
      <span class="channel-control__gamut-ranges" aria-hidden="true">
        <span
          v-for="(section, index) in guideSections"
          :key="`${section.tone}-range-${index}`"
          class="channel-control__gamut-range"
          :data-gp-part="gpPart.gamutInterval"
          :data-gp-gamut="section.tone"
          :class="`channel-control__gamut-range--${section.tone}`"
          :style="sectionStyle(section)"
          :data-gamut-range="section.tone"
          :data-range-start="section.start"
          :data-range-end="section.end"
        />
      </span>
      <span v-for="marker in markers" :key="marker.id" class="sr-only" data-gp-visually-hidden>{{
        marker.label
      }}</span>
      <span
        v-show="warningVisible"
        class="channel-control__warning"
        :data-gp-part="gpPart.warning"
        :data-gp-warning="String(warningVisible)"
        :style="warningStyle"
        data-gamut-warning="linear"
        :data-warning-channel="channel.toLowerCase()"
        :data-warning-position="Math.min(1, Math.max(0, warningPosition))"
        :data-warning-side="warningPlacement.side"
        :data-warning-obstacle-count="warningObstacles.length"
        :data-visible="warningVisible ? 'true' : 'false'"
        aria-hidden="true"
      >
        <GamutWarningGlyph />
      </span>
      <input
        ref="rangeElement"
        :id="id"
        class="channel-control__range"
        :data-gp-part="gpPart.nativeRange"
        type="range"
        :aria-describedby="describedBy"
        :aria-label="label"
        :value="displayedRangeValue"
        :min="min"
        :max="max"
        :step="step"
        @pointerdown="markPointerFocus"
        @blur="clearPointerFocus"
        @keydown="clearPointerFocus"
      />
      <span
        v-if="boundaryPreviewSection && boundaryPreviewColor"
        class="channel-control__boundary-preview-position"
        aria-hidden="true"
      >
        <span
          class="channel-control__boundary-preview"
          :data-gp-part="gpPart.boundaryPreview"
          :style="{
            left: `${boundaryPreviewSection.end * 100}%`,
            background: boundaryPreviewColor,
          }"
          data-slider-boundary-preview
        />
      </span>
    </div>

    <p v-if="help" :id="helpId" class="channel-control__help">{{ help }}</p>
    <span
      v-if="warningDescriptionId"
      :id="warningDescriptionId"
      class="sr-only"
      data-gp-visually-hidden
    >
      {{ warningLabel }}
    </span>
  </div>
</template>
