// packages/react/src/components/GamutWarningGlyph.tsx
import { PICKER_WARNING_GLYPH_SIZE } from "@gamut-plane/render";
import { gpPart } from "@gamut-plane/ui";

export function GamutWarningGlyph() {
  return (
    <svg
      className="gpr-gamut-warning-glyph"
      data-gp-part={gpPart.warningGlyph}
      width={PICKER_WARNING_GLYPH_SIZE}
      height={PICKER_WARNING_GLYPH_SIZE}
      viewBox="0 0 16 16"
      fill="none"
      aria-hidden="true"
      focusable="false"
      data-gamut-warning-glyph=""
    >
      <path d="M8 1.5 14.25 13.5H1.75Z" />
    </svg>
  );
}

// packages/vue/src/components/GamutWarningGlyph.vue
<script setup lang="ts">
import { PICKER_WARNING_GLYPH_SIZE } from "@gamut-plane/render";
import { gamutWarningGlyph, gpPart } from "@gamut-plane/ui";
</script>

<template>
  <svg
    class="gamut-warning-glyph"
    :data-gp-part="gpPart.warningGlyph"
    :width="PICKER_WARNING_GLYPH_SIZE"
    :height="PICKER_WARNING_GLYPH_SIZE"
    :viewBox="gamutWarningGlyph.viewBox"
    fill="none"
    aria-hidden="true"
    focusable="false"
    data-gamut-warning-glyph
  >
    <path :d="gamutWarningGlyph.path" />
  </svg>
</template>
