// packages/react/src/components/NumericInput.tsx
import { useLayoutEffect, useRef, type ComponentPropsWithoutRef } from "react";
import { useCommitted } from "../hooks/useCommitted.js";
import { gpPart } from "@gamut-plane/ui";

interface NumericInputProps extends Omit<
  ComponentPropsWithoutRef<"input">,
  | "value"
  | "defaultValue"
  | "onChange"
  | "onInput"
  | "onBlur"
  | "onKeyDown"
  | "type"
  | "min"
  | "max"
  | "step"
> {
  value: number;
  min: number;
  max?: number | undefined;
  step: number;
  precision: number;
  onComplete: (value: number) => void;
  onCancel: (() => void) | undefined;
}

/** The native number input owns its temporary text/bad-input/IME buffer. */
export function NumericInput(props: NumericInputProps) {
  const { value, min, max, step, precision, onComplete, onCancel, ...dom } = props;
  const input = useRef<HTMLInputElement>(null);
  const current = useCommitted({ value, precision, min, max, onComplete, onCancel });
  const resetDraft = useRef<(() => void) | null>(null);
  useLayoutEffect(() => {
    const element = input.current!;
    let dirty = false;
    let composing = false;
    let revision = 0;
    let disposed = false;
    function reset() {
      dirty = false;
      element.value = current.current!.value.toFixed(current.current!.precision);
    }
    resetDraft.current = () => {
      revision++;
      reset();
    };
    function edit() {
      revision++;
      dirty = true;
    }
    function complete() {
      if (!dirty || composing) return;
      dirty = false;
      const completedRevision = revision;
      const numeric = element.valueAsNumber;
      const committed = current.current!;
      if (Number.isFinite(numeric))
        committed.onComplete(Math.min(committed.max ?? Infinity, Math.max(committed.min, numeric)));
      queueMicrotask(() => {
        if (!disposed && revision === completedRevision) reset();
      });
    }
    function key(event: KeyboardEvent) {
      if (event.isComposing || composing) return;
      if (event.key === "Enter") {
        event.preventDefault();
        complete();
      } else if (event.key === "Escape" && dirty) {
        event.preventDefault();
        event.stopPropagation();
        revision++;
        reset();
        current.current!.onCancel?.();
      }
    }
    function compositionStart() {
      composing = true;
    }
    function compositionEnd() {
      composing = false;
    }
    element.addEventListener("input", edit);
    element.addEventListener("change", complete);
    element.addEventListener("blur", complete);
    element.addEventListener("keydown", key);
    element.addEventListener("compositionstart", compositionStart);
    element.addEventListener("compositionend", compositionEnd);
    return () => {
      disposed = true;
      resetDraft.current = null;
      element.removeEventListener("input", edit);
      element.removeEventListener("change", complete);
      element.removeEventListener("blur", complete);
      element.removeEventListener("keydown", key);
      element.removeEventListener("compositionstart", compositionStart);
      element.removeEventListener("compositionend", compositionEnd);
    };
  }, [current]);
  useLayoutEffect(() => {
    resetDraft.current?.();
  }, [value, precision]);
  return (
    <input
      {...dom}
      ref={input}
      type="number"
      data-gp-part={gpPart.numericInput}
      inputMode="decimal"
      dir="ltr"
      defaultValue={value.toFixed(precision)}
      min={min}
      max={max}
      step={step}
    />
  );
}

// packages/vue/src/components/NumericInput.vue
<script setup lang="ts">
import { nextTick, ref, watch } from "vue";
import { gpPart } from "@gamut-plane/ui";

const props = defineProps<{
  modelValue: number;
  min: number;
  max?: number;
  step: number;
  precision: number;
}>();
const emit = defineEmits<{
  "update:modelValue": [value: number];
  commit: [value: number];
  cancel: [];
}>();
const input = ref<HTMLInputElement>();
const draft = ref(props.modelValue.toFixed(props.precision));
let dirty = false;
let revision = 0;

function reset(): void {
  dirty = false;
  draft.value = props.modelValue.toFixed(props.precision);
  // Also clear the browser's internal bad-input buffer (e.g. a lone minus sign).
  if (input.value) input.value.value = draft.value;
}

function edit(event: Event): void {
  revision += 1;
  dirty = true;
  draft.value = (event.currentTarget as HTMLInputElement).value;
}

function complete(): void {
  if (!dirty) return;
  const value = input.value?.valueAsNumber;
  dirty = false;
  const completedRevision = revision;
  if (value !== undefined && Number.isFinite(value)) {
    const next = Math.min(props.max ?? Infinity, Math.max(props.min, value));
    emit("update:modelValue", next);
    emit("commit", next);
  }
  void nextTick(() => {
    if (revision === completedRevision) reset();
  });
}

function keydown(event: KeyboardEvent): void {
  if (event.isComposing) return;
  if (event.key === "Enter") {
    event.preventDefault();
    complete();
  } else if (event.key === "Escape" && dirty) {
    event.preventDefault();
    event.stopPropagation();
    revision += 1;
    reset();
    emit("cancel");
  }
}

watch(() => props.modelValue, reset);
</script>

<template>
  <input
    ref="input"
    type="number"
    :data-gp-part="gpPart.numericInput"
    inputmode="decimal"
    :value="draft"
    :min="min"
    :max="max"
    :step="step"
    @input="edit"
    @change="complete"
    @blur="complete"
    @keydown="keydown"
  />
</template>
